## Missão: Analisar o Comportamento de Compra de Consumidores.

Você recebeu a tarefa de analisar os dados de compras de um web site! Os dados estão no formato JSON e disponíveis junto com este notebook.

No site, cada usuário efetua login usando sua conta pessoal e pode adquirir produtos à medida que navega pela lista de produtos oferecidos. Cada produto possui um valor de venda. Dados de idade e sexo de cada usuário foram coletados e estão fornecidos no arquivo JSON.

Seu trabalho é entregar uma análise de comportamento de compra dos consumidores. Esse é um tipo de atividade comum realizado por Cientistas de Dados e o resultado deste trabalho pode ser usado, por exemplo, para alimentar um modelo de Machine Learning e fazer previsões sobre comportamentos futuros.

Mas nesta missão você vai analisar o comportamento de compra dos consumidores usando o pacote Pandas da linguagem Python e seu relatório final deve incluir cada um dos seguintes itens:

**Contagem de Consumidores**

* Número total de consumidores


**Análise Geral de Compras**

* Número de itens exclusivos
* Preço médio de compra
* Número total de compras
* Rendimento total


**Informações Demográficas Por Gênero**

* Porcentagem e contagem de compradores masculinos
* Porcentagem e contagem de compradores do sexo feminino
* Porcentagem e contagem de outros / não divulgados


**Análise de Compras Por Gênero**

* Número de compras
* Preço médio de compra
* Valor Total de Compra
* Compras for faixa etária


**Identifique os 5 principais compradores pelo valor total de compra e, em seguida, liste (em uma tabela):**

* Login
* Número de compras
* Preço médio de compra
* Valor Total de Compra


**Identifique os 5 itens mais populares por contagem de compras e, em seguida, liste (em uma tabela):**

* ID do item
* Nome do item
* Número de compras
* Preço do item
* Valor Total de Compra
* Itens mais lucrativos


**Identifique os 5 itens mais lucrativos pelo valor total de compra e, em seguida, liste (em uma tabela):**

* ID do item
* Nome do item
* Número de compras
* Preço do item
* Valor Total de Compra


**Como considerações finais:**

* Seu script deve funcionar para o conjunto de dados fornecido.
* Você deve usar a Biblioteca Pandas e o Jupyter Notebook.

In [1]:
# importando pacotes necessários
import numpy as np
import pandas as pd

In [5]:
# Salvando os dados em uma variável

data = pd.read_json("dados_compras.json")
data

,Login,Idade,Sexo,Item ID,Nome do Item,Valor
0,Aelalis34,38,Masculino,165,Bone Crushing Silver Skewer,3.37
1,Eolo46,21,Masculino,119,"Stormbringer, Dark Blade of Ending Misery",2.32
2,Assastnya25,34,Masculino,174,Primitive Blade,2.46
3,Pheusrical25,21,Masculino,92,Final Critic,1.36
4,Aela59,23,Masculino,63,Stormfury Mace,1.27
...,...,...,...,...,...,...
775,Eural50,22,Masculino,98,"Deadline, Voice Of Subtlety",3.62
776,Lirtossa78,14,Masculino,104,Gladiator's Glaive,1.36
777,Tillyrin30,20,Masculino,117,"Heartstriker, Legacy of the Light",4.15
778,Quelaton80,20,Masculino,75,Brutality Ivory Warmace,1.72
779,Alim85,23,Feminino,107,"Splitter, Foe Of Subtlety",3.61

**Contagem de Consumidores**

* Número total de consumidores

In [10]:
contagem = data["Login"].count()

print(f"O número total de consumidores é {contagem}")

O número total de consumidores é 780

**Análise Geral de Compras**

* Número de itens exclusivos
* Preço médio de compra
* Número total de compras
* Rendimento total

In [19]:
# Número de itens exclusivos
data.nunique()

Login           573
Idade            37
Sexo              3
Item ID         183
Nome do Item    179
Valor           152
dtype: int64

In [30]:
# Preço médio de compra
preco_medio = data['Valor'].mean().round(2)

print(f'O preço médio do valor é de R${preco_medio} reais.')

O preço médio do valor é de R$2.93 reais.

In [31]:
# Número total de compras
total_compras = data['Valor'].count()

print(f'O número total de compras é de {total_compras}.')

O número total de compras é de 780.

In [33]:
# Rendimento total

renda = data['Valor'].sum()

print(f'O rendimento total é de R${renda} reais.')

O rendimento total é de R$2286.33 reais.

**Informações Demográficas Por Gênero**

* Porcentagem e contagem de compradores masculinos
* Porcentagem e contagem de compradores do sexo feminino
* Porcentagem e contagem de outros / não divulgados

In [50]:
# Porcentagem e contagem de compradores masculinos

contagem_masc = data['Sexo'].value_counts()['Masculino']
porcentagem_masc = (contagem_masc/total_compras * 100).round(2)

print(f"A contagem masculina corresponde a {contagem_masc}, isso representa {porcentagem_masc}% da amostragem.")

A contagem masculina corresponde a 633, isso representa 81.15% da amostragem.

In [52]:
# Porcentagem e contagem de compradores do sexo feminino

contagem_fem = data['Sexo'].value_counts()['Feminino']
porcentagem_fem = (contagem_fem/total_compras *100).round(2)

print(f'A contagem feminina corresponde a {contagem_fem}, isso representa {porcentagem_fem}% da amostragem.')

A contagem feminina corresponde a 136, isso representa 17.44% da amostragem.

In [60]:
# Porcentagem e contagem de outros / não divulgados

data['Sexo'].unique() # Descobrindo como está escrito corretamente o nome na coluna

contagem_outro = data['Sexo'].value_counts()['Outro / Não Divulgado']
porcentagem_outro = (contagem_outro/total_compras *100).round(2)

print(f'A contagem de "Outro / Não Divulgado" corresponde a {contagem_outro}, isso representa {porcentagem_outro}% da amostragem.')

A contagem de "Outro / Não Divulgado" corresponde a 11, isso representa 1.41% da amostragem.

**Análise de Compras Por Gênero**

* Número de compras
* Preço médio de compra
* Valor Total de Compra
* Compras for faixa etária

In [77]:
# Número de compras
compras_masc = data[data['Sexo'] == 'Masculino']['Valor'].count()
compras_fem = data[data['Sexo'] == 'Feminino']['Valor'].count()
compras_outro = data[data['Sexo'] == 'Outro / Não Divulgado']['Valor'].count()

print(f'O número de compras do gênero masculino é de {compras_masc}.')
print(f'O número de compras do gênero feminino é de {compras_fem}.')
print(f'O número de compras do gênero "Outro / Não Divulgado" é de {compras_outro}.')

O número de compras do gênero masculino é de 633.
O número de compras do gênero feminino é de 136.
O número de compras do gênero "Outro / Não Divulgado" é de 11.

In [86]:
# Preço médio de compra
preco_medio_masc = data[data['Sexo'] == 'Masculino']['Valor'].mean().round(2)
preco_medio_fem = data[data['Sexo'] == 'Feminino']['Valor'].mean().round(2)
preco_medio_outro = data[data['Sexo'] == 'Outro / Não Divulgado']['Valor'].mean().round(2)

print(f'O número de preço médio do gênero masculino foi de R${preco_medio_masc} reais.')
print(f'O número de preço médio do gênero feminino foi de R${preco_medio_fem} reais.')
print(f'O número de preço mfoidio do gênero "Outro / Não Divulgado" foi de R${preco_medio_outro} reais.')

O número de preço médio do gênero masculino foi de R$2.95 reais.
O número de preço médio do gênero feminino foi de R$2.82 reais.
O número de preço mfoidio do gênero "Outro / Não Divulgado" foi de R$3.25 reais.

In [99]:
# Valor Total de Compra
total_compras_masc = data[data['Sexo'] == 'Masculino']['Valor'].sum().round(2)
total_compras_fem = data[data['Sexo'] == 'Feminino']['Valor'].sum().round(2)
total_compras_outro = data[data['Sexo'] == 'Outro / Não Divulgado']['Valor'].sum().round(2)

print(f'O valor total de compras do gênero masculino foi de R${total_compras_masc} reais.')
print(f'O valor total de compras do gênero feminino foi de R${total_compras_fem} reais.')
print(f'O valor total de compras do gênero "Outro / Não Divulgado" foi de R${total_compras_outro} reais.')

O valor total de compras do gênero masculino foi de R$1867.68 reais.
O valor total de compras do gênero feminino foi de R$382.91 reais.
O valor total de compras do gênero "Outro / Não Divulgado" foi de R$35.74 reais.

In [100]:
# Compras por faixa etária
compras_crianca = data[data['Idade'] < 10]['Valor'].count()
compras_adolescente = data[(data['Idade'] >= 10) & (data['Idade'] <= 17)]['Valor'].count()
compras_adulto = data[(data['Idade'] >= 18) & (data['Idade'] <= 59)]['Valor'].count()
compras_idosos = data[data['Idade'] >= 60]['Valor'].count()

print(f'O número de crianças que compraram corresponde a {compras_crianca}.')
print(f'O número de adolescentes que compraram corresponde a {compras_adolescente}.')
print(f'O número de adultos que compraram corresponde a {compras_adulto}.')
print(f'O número de idosos que compraram corresponde a {compras_idosos}.')

O número de crianças que compraram corresponde a 28.
O número de adolescentes que compraram corresponde a 122.
O número de adultos que compraram corresponde a 630.
O número de idosos que compraram corresponde a 0.

**Identifique os 5 principais compradores pelo valor total de compra e, em seguida, liste (em uma tabela):**

* Login
* Número de compras
* Preço médio de compra
* Valor Total de Compra

In [105]:
# Agrupa as compras por Login
top_compradores = (
    data.groupby('Login')

        # Essa função aplica cálculos sobre cada grupo de compradores
        .agg(
            **{ # ** permite nomear as colunas de saída diretamente no agg()
                'Número de compras': ('Valor', 'count'),     # Traz a quantidade de compras
                'Preço médio de compra': ('Valor', 'mean'),  # Traz a média de compra
                'Valor Total de Compra': ('Valor', 'sum')    # Valor total da compra
              }
            )
        )

# Seleciona os 5 maiores compradores pelo valor total
top_compradores = (
    top_compradores

        # ordena do maior valor total para o menor
        .sort_values('Valor Total de Compra', ascending=False)
        # pega os 5 maiores
        .head(5)
)

# Formata os valores monetários
top_compradores['Preço médio de compra'] = top_compradores['Preço médio de compra'].map('${:.2f}'.format)
top_compradores['Valor Total de Compra'] = top_compradores['Valor Total de Compra'].map('${:.2f}'.format)

top_compradores

             Número de compras Preço médio de compra Valor Total de Compra
Login
Undirrala66                  5                 $3.41                $17.06
Saedue76                     4                 $3.39                $13.56
Mindimnya67                  4                 $3.19                $12.74
Haellysu29                   3                 $4.24                $12.73
Eoda93                       3                 $3.86                $11.58

**Identifique os 5 itens mais populares por contagem de compras e, em seguida, liste (em uma tabela):**

* ID do item
* Nome do item
* Número de compras
* Preço do item
* Valor Total de Compra
* Itens mais lucrativos

In [109]:
# Agrupa os dados por ID e Nome do item
itens_populares = (
    data.groupby(['Item ID', 'Nome do Item'])

    # Essa função aplica cálculos sobre cada grupo de compradores
    .agg(
        **{  # ** permite nomear as colunas de saída diretamente no agg()
            'Número de compras': ('Valor', 'count'),      # Conta quantas compras o item teve
            'Preço do item': ('Valor', 'mean'),           # Calcula o preço médio do item
            'Valor Total de Compra': ('Valor', 'sum')     # Soma o valor total vendido
        }
    )

    # Ordena do item mais comprado para o menos comprado
    .sort_values('Número de compras', ascending=False)

    # Seleciona apenas os 5 primeiros itens
    .head(5)
)

# Formata o preço do item com cifrão e duas casas decimais
itens_populares['Preço do item'] = itens_populares['Preço do item'].map('${:.2f}'.format)

# Formata o valor total de compra com cifrão e duas casas decimais
itens_populares['Valor Total de Compra'] = itens_populares['Valor Total de Compra'].map('${:.2f}'.format)

# Exibe a tabela final
itens_populares

,,Número de compras,Preço do item,Valor Total de Compra
Item ID,Nome do Item,,,
39,"Betrayal, Whisper of Grieving Widows",11,$2.35,$25.85
84,Arcane Gem,11,$2.23,$24.53
34,Retribution Axe,9,$4.14,$37.26
31,Trickster,9,$2.07,$18.63
13,Serenity,9,$1.49,$13.41

**Identifique os 5 itens mais lucrativos pelo valor total de compra e, em seguida, liste (em uma tabela):**

* ID do item
* Nome do item
* Número de compras
* Preço do item
* Valor Total de Compra

In [110]:
# Agrupa os dados por ID e Nome do item
itens_populares = (
    data.groupby(['Item ID', 'Nome do Item'])

    # Essa função aplica cálculos sobre cada grupo de compradores
    .agg(
        **{  # ** permite nomear as colunas de saída diretamente no agg()
            'Número de compras': ('Valor', 'count'),      # Conta quantas compras o item teve
            'Preço do item': ('Valor', 'mean'),           # Calcula o preço médio do item
            'Valor Total de Compra': ('Valor', 'sum')     # Soma o valor total vendido
        }
    )

    # Ordena do item mais comprado para o menos comprado
    .sort_values('Valor Total de Compra', ascending=False)

    # Seleciona apenas os 5 primeiros itens
    .head(5)
)

# Formata o preço do item com cifrão e duas casas decimais
itens_populares['Preço do item'] = itens_populares['Preço do item'].map('${:.2f}'.format)

# Formata o valor total de compra com cifrão e duas casas decimais
itens_populares['Valor Total de Compra'] = itens_populares['Valor Total de Compra'].map('${:.2f}'.format)

# Exibe a tabela final
itens_populares

,,Número de compras,Preço do item,Valor Total de Compra
Item ID,Nome do Item,,,
34,Retribution Axe,9,$4.14,$37.26
115,Spectral Diamond Doomblade,7,$4.25,$29.75
32,Orenmir,6,$4.95,$29.70
103,Singed Scalpel,6,$4.87,$29.22
107,"Splitter, Foe Of Subtlety",8,$3.61,$28.88